// <auto-generated />
using System;
using CoreSBBL.Logging.Infrastructure.TS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreSBBL.Migrations
{
    [DbContext(typeof(LogsContextTC))]
    [Migration("20230611175457_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreSBBL.Logging.Models.DAL.TC.LogsDALEF", b =>
                {
                    b.Property<int>("IdInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInt"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("IdInt")
                        .HasName("Logs_Id");

                    b.HasIndex("LabelId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("CoreSBBL.Logging.Models.DAL.TC.LogsLabelDALEF", b =>
                {
                    b.Property<int>("IdInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInt"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("IdInt")
                        .HasName("LogsLabel_Id");

                    b.ToTable("LogsLabel", (string)null);
                });

            modelBuilder.Entity("CoreSBBL.Logging.Models.DAL.TC.LogsTagDALEF", b =>
                {
                    b.Property<int>("IdInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInt"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInt")
                        .HasName("LogsTags_Id");

                    b.ToTable("LogsTags", (string)null);
                });

            modelBuilder.Entity("LogsToTags", b =>
                {
                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("LogId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("LogsToTags");
                });

            modelBuilder.Entity("CoreSBBL.Logging.Models.DAL.TC.LogsDALEF", b =>
                {
                    b.HasOne("CoreSBBL.Logging.Models.DAL.TC.LogsLabelDALEF", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("LogsToTags", b =>
                {
                    b.HasOne("CoreSBBL.Logging.Models.DAL.TC.LogsDALEF", null)
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreSBBL.Logging.Models.DAL.TC.LogsTagDALEF", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
